/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: potionstory.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @potionstory: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
			VarDef("lovepotionsarentreal", () => this.@lovepotionsarentreal, val => this.@lovepotionsarentreal = val);
			VarDef("mcknowsaboutgen", () => this.@mcknowsaboutgen, val => this.@mcknowsaboutgen = val);
			VarDef("mcknowsofproblem", () => this.@mcknowsofproblem, val => this.@mcknowsofproblem = val);
			VarDef("icanmakepotion", () => this.@icanmakepotion, val => this.@icanmakepotion = val);
			VarDef("questnotgiven", () => this.@questnotgiven, val => this.@questnotgiven = val);
		}

		public StoryVar @lovepotionsarentreal;
		public StoryVar @mcknowsaboutgen;
		public StoryVar @mcknowsofproblem;
		public StoryVar @icanmakepotion;
		public StoryVar @questnotgiven;
	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@potionstory()
	{
		this.StartPassage = "Start";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
		passage12_Init();
		passage13_Init();
		passage14_Init();
		passage15_Init();
		passage16_Init();
		passage17_Init();
		passage18_Init();
		passage19_Init();
		passage20_Init();
		passage21_Init();
		passage22_Init();
		passage23_Init();
		passage24_Init();
		passage25_Init();
		passage26_Init();
		passage27_Init();
		passage28_Init();
		passage29_Init();
		passage30_Init();
		passage31_Init();
		passage32_Init();
		passage33_Init();
		passage34_Init();
		passage35_Init();
		passage36_Init();
		passage37_Init();
		passage38_Init();
		passage39_Init();
		passage40_Init();
		passage41_Init();
		passage42_Init();
		passage43_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Start

	void passage1_Init()
	{
		this.Passages[@"Start"] = new StoryPassage(@"Start", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("Hey... uuh, hello. My name is Lecall.");
		yield return lineBreak();
		yield return text("I need your help. You're an alchemist, right?");
		yield return lineBreak();
		yield return link("Yeah.", "Yeah.", null);
		yield break;
	}


	// .............
	// #2: Yeah.

	void passage2_Init()
	{
		this.Passages[@"Yeah."] = new StoryPassage(@"Yeah.", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("Great! I... so you make potions and stuff then? And help people?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Sometimes...", "Sometimes...", null);
		yield break;
	}


	// .............
	// #3: Sometimes...

	void passage3_Init()
	{
		this.Passages[@"Sometimes..."] = new StoryPassage(@"Sometimes...", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("Can you... can you make a love potion?");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("I can pay.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("[");
		yield return text("thoughts: oh, no.]");
		yield return lineBreak();
		yield return link("Sorry. I don't do that kind of thing.", "Sorry. I don't do that kind of thing.", null);
		yield return lineBreak();
		yield return link("'sigh' ...Love potions aren't real.", "'sigh' ...Love potions aren't real.", null);
		yield return lineBreak();
		yield return link("Uhh, I need a little more information than that. Who's it for?", "Uhh, I need a little more information than that. Who's it for?", null);
		yield return lineBreak();
		yield return link("Sure. What do you need?", "Sure. What do you need?", null);
		yield break;
	}


	// .............
	// #4: Sorry. I don't do that kind of thing.

	void passage4_Init()
	{
		this.Passages[@"Sorry. I don't do that kind of thing."] = new StoryPassage(@"Sorry. I don't do that kind of thing.", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("No? Damn...");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Do you... know of any other alchemists I can ask?");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("'sigh' ...Love potions aren't real.", "'sigh' ...Love potions aren't real.", null);
		yield return lineBreak();
		yield return link("No, sorry.", "No, sorry.", null);
		yield break;
	}


	// .............
	// #5: 'sigh' ...Love potions aren't real.

	void passage5_Init()
	{
		this.Passages[@"'sigh' ...Love potions aren't real."] = new StoryPassage(@"'sigh' ...Love potions aren't real.", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("...What?");
		yield return lineBreak();
		yield return text("What do you mean?");
		yield return lineBreak();
		yield return text("My... my aunt told me you did things like that. That her uncle used one on her.");
		yield return lineBreak();
		yield return lineBreak();
		Vars.lovepotionsarentreal  = true;
		yield return lineBreak();
		yield return link("Well, your aunt is wrong. Love potions don't exist.", "Well, your aunt is wrong. Love potions don't exist.", null);
		yield break;
	}


	// .............
	// #6: Uhh, I need a little more information than that. Who's it for?

	void passage6_Init()
	{
		this.Passages[@"Uhh, I need a little more information than that. Who's it for?"] = new StoryPassage(@"Uhh, I need a little more information than that. Who's it for?", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("A... girl I like.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Who is she?", "Who is she?", null);
		yield return lineBreak();
		yield return link("And why do you want to give her a love potion?", "why", null);
		yield break;
	}


	// .............
	// #7: Sure. What do you need?

	void passage7_Init()
	{
		this.Passages[@"Sure. What do you need?"] = new StoryPassage(@"Sure. What do you need?", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("A... love potion.");
		yield return lineBreak();
		yield return text("To make a person fall in love with me.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Who are we talking about?", "Who are we talking about?", null);
		yield return lineBreak();
		yield return link("Why?", "why", null);
		yield break;
	}


	// .............
	// #8: No, sorry.

	void passage8_Init()
	{
		this.Passages[@"No, sorry."] = new StoryPassage(@"No, sorry.", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("Oh... ok.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Well. If you hear of anyone, I live in the cobbler's shop down the street. I... could really use the help.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("I'll let you know if I hear of anyone.", "I'll let you know if I hear of anyone.", null);
		yield return lineBreak();
		yield return link("What's the problem? Maybe I can help in some other way?", "What's the problem? Maybe I can help in some other way?", null);
		yield break;
	}


	// .............
	// #9: I'll let you know if I hear of anyone.

	void passage9_Init()
	{
		this.Passages[@"I'll let you know if I hear of anyone."] = new StoryPassage(@"I'll let you know if I hear of anyone.", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text("[");
		yield return text("END]");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("[");
		yield return text("trigger conversation with him upon talking again.]");
		yield return lineBreak();
		yield return text("[");
		yield return text("no flags set, default quest interaction, new, that is...]");
		yield break;
	}


	// .............
	// #10: What's the problem? Maybe I can help in some other way?

	void passage10_Init()
	{
		this.Passages[@"What's the problem? Maybe I can help in some other way?"] = new StoryPassage(@"What's the problem? Maybe I can help in some other way?", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		yield return text("I... you can guess.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Is there a girl?", "Is there a girl?", null);
		yield break;
	}


	// .............
	// #11: Well, your aunt is wrong. Love potions don't exist.

	void passage11_Init()
	{
		this.Passages[@"Well, your aunt is wrong. Love potions don't exist."] = new StoryPassage(@"Well, your aunt is wrong. Love potions don't exist.", new string[]{  }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		yield return text("What... what am I supposed to do then?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("The old fashioned way, my friend.", "You figure it out", null);
		yield return lineBreak();
		yield return link("You figure it out", "You figure it out", null);
		yield break;
	}


	// .............
	// #12: Is there a girl?

	void passage12_Init()
	{
		this.Passages[@"Is there a girl?"] = new StoryPassage(@"Is there a girl?", new string[]{  }, passage12_Main);
	}

	IStoryThread passage12_Main()
	{
		yield return text("...Yes.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Who is she?", "Who is she?", null);
		yield break;
	}


	// .............
	// #13: You figure it out

	void passage13_Init()
	{
		this.Passages[@"You figure it out"] = new StoryPassage(@"You figure it out", new string[]{  }, passage13_Main);
	}

	IStoryThread passage13_Main()
	{
		yield return text("No. You're lying to me. There must other alchemists that do it, then.");
		yield return lineBreak();
		yield return text("Right? ");
		yield return lineBreak();
		yield return text("You just don't know how to.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Look. I don't have the time for this if you don't want to listen.", "Look. I don't have the time for this if you don't want to listen.", null);
		yield return lineBreak();
		yield return link("And you start critizicing me? Wow, yeah, now I want to work for you.", "And you start critizicing me? Wow, yeah, now I want to work for you.", null);
		yield break;
	}


	// .............
	// #14: Look. I don't have the time for this if you don't want to listen.

	void passage14_Init()
	{
		this.Passages[@"Look. I don't have the time for this if you don't want to listen."] = new StoryPassage(@"Look. I don't have the time for this if you don't want to listen.", new string[]{  }, passage14_Main);
	}

	IStoryThread passage14_Main()
	{
		yield return text("Whatever, I'm sorry to have bothered you. Raeth la'en.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Raeth la'en.", "Fine.", null);
		yield break;
	}


	// .............
	// #15: And you start critizicing me? Wow, yeah, now I want to work for you.

	void passage15_Init()
	{
		this.Passages[@"And you start critizicing me? Wow, yeah, now I want to work for you."] = new StoryPassage(@"And you start critizicing me? Wow, yeah, now I want to work for you.", new string[]{  }, passage15_Main);
	}

	IStoryThread passage15_Main()
	{
		yield return text("No, Sorry. You're right. I don't know anything about alchemy, I just go by what everyone knows, right? Like, it's no secret you all are able to control wraithfire. Why not love?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("...Sure. Well. Some of us might be able to do that. I'm not one of them, so don't clump us all together, a'ight?", "lump", null);
		yield break;
	}


	// .............
	// #16: Who is she?

	void passage16_Init()
	{
		this.Passages[@"Who is she?"] = new StoryPassage(@"Who is she?", new string[]{  }, passage16_Main);
	}

	IStoryThread passage16_Main()
	{
		yield return text("Her name's Gen--Gennae. She's a student at ");
		yield return text("[");
		yield return text("...]. She's smart and kind, and wonderful.");
		yield return lineBreak();
		yield return lineBreak();
		Vars.mcknowsaboutgen  = true;
		yield return lineBreak();
		yield return link("And you want to date her?", "And you want to date her?", null);
		yield break;
	}


	// .............
	// #17: And you want to date her?

	void passage17_Init()
	{
		this.Passages[@"And you want to date her?"] = new StoryPassage(@"And you want to date her?", new string[]{  }, passage17_Main);
	}

	IStoryThread passage17_Main()
	{
		yield return text("Yes.");
		yield return lineBreak();
		Vars.mcknowsofproblem  = true;
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Well, good luck with that.", "Well, good luck with that.", null);
		yield return lineBreak();
		yield return link("Have you tried asking her?", "Have you tried asking her?", null);
		yield break;
	}


	// .............
	// #18: Have you tried asking her?

	void passage18_Init()
	{
		this.Passages[@"Have you tried asking her?"] = new StoryPassage(@"Have you tried asking her?", new string[]{  }, passage18_Main);
	}

	IStoryThread passage18_Main()
	{
		yield return text("..I can't. She... I'll mess it up. Look like a fool.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("And you think a love potion will help?", "And you think a love potion will help?", null);
		yield return lineBreak();
		yield return link("You might do. But if she likes you back, it won't matter.", "You might do. But if she likes you back, it won't matter.", null);
		yield break;
	}


	// .............
	// #19: Well, good luck with that.

	void passage19_Init()
	{
		this.Passages[@"Well, good luck with that."] = new StoryPassage(@"Well, good luck with that.", new string[]{  }, passage19_Main);
	}

	IStoryThread passage19_Main()
	{
		yield return text("You can't help me?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("No. I'll let you know if I hear of anyone who can.", "I'll let you know if I hear of anyone2.", null);
		yield return lineBreak();
		yield return link("'sigh' ...Love potions aren't real.", "'sigh' ...Love potions aren't real.", null);
		yield break;
	}


	// .............
	// #20: why

	void passage20_Init()
	{
		this.Passages[@"why"] = new StoryPassage(@"why", new string[]{  }, passage20_Main);
	}

	IStoryThread passage20_Main()
	{
		yield return text("Because I'm in love with her.");
		yield return lineBreak();
		yield return text("And I want to be with her.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Sorry, then. I don't do personal cases.", "No, sorry.", null);
		yield return lineBreak();
		yield return link("Who is she?", "Who is she?", null);
		yield break;
	}


	// .............
	// #21: And you think a love potion will help?

	void passage21_Init()
	{
		this.Passages[@"And you think a love potion will help?"] = new StoryPassage(@"And you think a love potion will help?", new string[]{  }, passage21_Main);
	}

	IStoryThread passage21_Main()
	{
		yield return text("Well... yes.");
		yield return lineBreak();
		yield return text("If I can only get her to see me, notice me. Maybe I can talk to her again.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("[");
		yield return text("tought: wow, a lot to unpack there. This could take a while...]");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("The best way to get her to notice you is to talk to her.", "The best way to get her to notice you is to talk to her.", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #22: The best way to get her to notice you is to talk to her.

	void passage22_Init()
	{
		this.Passages[@"The best way to get her to notice you is to talk to her."] = new StoryPassage(@"The best way to get her to notice you is to talk to her.", new string[]{  }, passage22_Main);
	}

	IStoryThread passage22_Main()
	{
		yield return text("But I can't.");
		yield return lineBreak();
		yield return text("I... I'm too nervous. Around her, I... lose my mouth. I can't talk.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("It's hard. I'm not denying you that. I don't really know why I'm telling you this, can't say I'm any more experienced in it myself. But I know any kind of love potion won't help.", "It's hard", null);
		yield break;
	}


	// .............
	// #23: It's hard

	void passage23_Init()
	{
		this.Passages[@"It's hard"] = new StoryPassage(@"It's hard", new string[]{  }, passage23_Main);
	}

	IStoryThread passage23_Main()
	{
		yield return text("Why? How can you be sure?");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("'sigh' ...Love potions aren't real.", "'sigh' ...Love potions aren't real.", null);
		yield return lineBreak();
		yield return link("*Lie*...I've seen it before. A friend of mine tried to create a love potion. It only worked while the potion was in effect. The day after, the other person was furious.", "furious", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #24: You might do. But if she likes you back, it won't matter.

	void passage24_Init()
	{
		this.Passages[@"You might do. But if she likes you back, it won't matter."] = new StoryPassage(@"You might do. But if she likes you back, it won't matter.", new string[]{  }, passage24_Main);
	}

	IStoryThread passage24_Main()
	{
		yield return text("...No. I can't. I need a love potion.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("If I can only get her to see me... If she can pause and listen, I might be able to talk to her.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Just talk to her. It'll work.", "The best way to get her to notice you is to talk to her.", null);
		yield break;
	}


	// .............
	// #25: furious

	void passage25_Init()
	{
		this.Passages[@"furious"] = new StoryPassage(@"furious", new string[]{  }, passage25_Main);
	}

	IStoryThread passage25_Main()
	{
		yield return text("Really?");
		yield return lineBreak();
		yield return text("But... aren't love potions supposed to harbour love? Create the spark that otherwheres never existed? Conjoin the two flowers in the wind and make them dance?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("You've been reading too many fairy tales.", "fairy tales", null);
		yield break;
	}


	// .............
	// #26: fairy tales

	void passage26_Init()
	{
		this.Passages[@"fairy tales"] = new StoryPassage(@"fairy tales", new string[]{  }, passage26_Main);
	}

	IStoryThread passage26_Main()
	{
		yield return text("I...");
		yield return lineBreak();
		yield return text("I just need a solution. I don't care if it might not work. I'm willing to try it. I don't have any other choice.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("'sigh' ...Love potions aren't real.", "'sigh' ...Love potions aren't real.", null);
		yield return lineBreak();
		yield return link("You do. But not one I can make for you.", "You do. But not one I can make for you.", null);
		yield return lineBreak();
		yield return link("Fine. I'll make you a love potion then.", "All right.", null);
		yield break;
	}


	// .............
	// #27: Who are we talking about?

	void passage27_Init()
	{
		this.Passages[@"Who are we talking about?"] = new StoryPassage(@"Who are we talking about?", new string[]{  }, passage27_Main);
	}

	IStoryThread passage27_Main()
	{
		yield return text("Her name's Gen--Gennae. She's a student at ");
		yield return text("[");
		yield return text("...]. She's smart and kind, and wonderful.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		Vars.mcknowsaboutgen  = true;
		yield return lineBreak();
		yield return link("All right.", "All right.", null);
		yield break;
	}


	// .............
	// #28: All right.

	void passage28_Init()
	{
		this.Passages[@"All right."] = new StoryPassage(@"All right.", new string[]{  }, passage28_Main);
	}

	IStoryThread passage28_Main()
	{
		yield return text("Really? You'll do it?");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		Vars.icanmakepotion  = true;
		yield return lineBreak();
		yield return link("It's not cheap though. Love potions are dangerous work.", "Dangerous", null);
		yield break;
	}


	// .............
	// #29: Where can I find her?

	void passage29_Init()
	{
		this.Passages[@"Where can I find her?"] = new StoryPassage(@"Where can I find her?", new string[]{  }, passage29_Main);
	}

	IStoryThread passage29_Main()
	{
		yield return text("...She's usually sits around after school in the park down the corner and reads, until evening time. You can find her there.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		if(Vars.icanmakepotion == true) {
			yield return lineBreak();
			yield return text("You'll make the potion?");
			yield return lineBreak();
			yield return lineBreak();
			yield return link("Yes", "I promise.", null);
			yield return lineBreak();
		}
		else {
			yield return lineBreak();
			yield return text("You promise you'll do it?");
			yield return lineBreak();
			yield return lineBreak();
			yield return link("I'll return to you when I have something", "I promise.", null);
			yield return lineBreak();
		}
		yield break;
	}


	// .............
	// #30: You do. But not one I can make for you.

	void passage30_Init()
	{
		this.Passages[@"You do. But not one I can make for you."] = new StoryPassage(@"You do. But not one I can make for you.", new string[]{  }, passage30_Main);
	}

	IStoryThread passage30_Main()
	{
		yield return text("Well...");
		yield return lineBreak();
		yield return text("Let me know if you find anyone who can.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("You know what? I'll help you. I have an idea, but you have to let me trust you, ok?", "trust", null);
		yield return lineBreak();
		yield return link("I will", "I'll let you know if I hear of anyone2.", null);
		yield break;
	}


	// .............
	// #31: trust

	void passage31_Init()
	{
		this.Passages[@"trust"] = new StoryPassage(@"trust", new string[]{  }, passage31_Main);
	}

	IStoryThread passage31_Main()
	{
		yield return text("Trust you?");
		yield return lineBreak();
		yield return text("I'm not sure... What are you going to do?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("I can't make you a love potion, but I can do something else.", "I can't make you a love potion, but I can do something else.", null);
		yield break;
	}


	// .............
	// #32: I can't make you a love potion, but I can do something else.

	void passage32_Init()
	{
		this.Passages[@"I can't make you a love potion, but I can do something else."] = new StoryPassage(@"I can't make you a love potion, but I can do something else.", new string[]{  }, passage32_Main);
	}

	IStoryThread passage32_Main()
	{
		yield return text("What?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Ah, trust me.", "Ah, trust me.", null);
		yield return lineBreak();
		yield return link("I'm going to talk to her.", "I'm going to talk to her.", null);
		yield break;
	}


	// .............
	// #33: I'm going to talk to her.

	void passage33_Init()
	{
		this.Passages[@"I'm going to talk to her."] = new StoryPassage(@"I'm going to talk to her.", new string[]{  }, passage33_Main);
	}

	IStoryThread passage33_Main()
	{
		yield return text("W-what? ");
		yield return lineBreak();
		yield return text("No. You cannot. You must not. It'll ruin everything.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("I need to... look. Even if I am to create a potion, anyway, I need to speak with her. Potions are tailored to the person, so I can't make anything without knowing how she is.", "the only way", null);
		yield break;
	}


	// .............
	// #34: Ah, trust me.

	void passage34_Init()
	{
		this.Passages[@"Ah, trust me."] = new StoryPassage(@"Ah, trust me.", new string[]{  }, passage34_Main);
	}

	IStoryThread passage34_Main()
	{
		yield return text("I'm not sure about this. I might go to another alchemist instead?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("No, I promise, no one will be able to deal with it any better.", "No, I promise, no one will be able to deal with it any better.", null);
		yield break;
	}


	// .............
	// #35: Dangerous

	void passage35_Init()
	{
		this.Passages[@"Dangerous"] = new StoryPassage(@"Dangerous", new string[]{  }, passage35_Main);
	}

	IStoryThread passage35_Main()
	{
		yield return text("Ok. Ok, no that's fine. I can pay.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("When do you want it by?", "When do you want it by?", null);
		yield break;
	}


	// .............
	// #36: When do you want it by?

	void passage36_Init()
	{
		this.Passages[@"When do you want it by?"] = new StoryPassage(@"When do you want it by?", new string[]{  }, passage36_Main);
	}

	IStoryThread passage36_Main()
	{
		yield return text("As soon as possible, really. I'm dying every day I sit here in loneliness.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Last thing. Where can I find her? I need to tailor love potions to the person. So I need to speak with her.", "Where can I find her?", null);
		yield break;
	}


	// .............
	// #37: No, I promise, no one will be able to deal with it any better.

	void passage37_Init()
	{
		this.Passages[@"No, I promise, no one will be able to deal with it any better."] = new StoryPassage(@"No, I promise, no one will be able to deal with it any better.", new string[]{  }, passage37_Main);
	}

	IStoryThread passage37_Main()
	{
		yield return text("How can you be so sure?");
		yield return lineBreak();
		yield return text("No, if you don't want to even tell me what you're doing, I can find someone else to help.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Fine. See you around, then.", "Fine.", null);
		yield return lineBreak();
		yield return link("Ok, look. I'm going to talk to her", "I'm going to talk to her.", null);
		yield break;
	}


	// .............
	// #38: I promise.

	void passage38_Init()
	{
		this.Passages[@"I promise."] = new StoryPassage(@"I promise.", new string[]{  }, passage38_Main);
	}

	IStoryThread passage38_Main()
	{
		yield return text("[");
		yield return text("END - promise made]");
		yield break;
	}


	// .............
	// #39: I'll let you know if I hear of anyone2.

	void passage39_Init()
	{
		this.Passages[@"I'll let you know if I hear of anyone2."] = new StoryPassage(@"I'll let you know if I hear of anyone2.", new string[]{  }, passage39_Main);
	}

	IStoryThread passage39_Main()
	{
		yield return text("[");
		yield return text("END]");
		yield return lineBreak();
		Vars.questnotgiven  = true;
		yield return lineBreak();
		yield return text("[");
		yield return text("trigger conversation with him upon talking again.]");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #40: Fine.

	void passage40_Init()
	{
		this.Passages[@"Fine."] = new StoryPassage(@"Fine.", new string[]{  }, passage40_Main);
	}

	IStoryThread passage40_Main()
	{
		yield return text("[");
		yield return text("END]");
		yield return lineBreak();
		yield return lineBreak();
		Vars.questnotgiven  = true;
		yield return lineBreak();
		yield return text("[");
		yield return text("quest state enters not-allowed state, but mc can still talk to gennae or even make the potion]");
		yield break;
	}


	// .............
	// #41: the only way

	void passage41_Init()
	{
		this.Passages[@"the only way"] = new StoryPassage(@"the only way", new string[]{  }, passage41_Main);
	}

	IStoryThread passage41_Main()
	{
		yield return text("And that's the only way?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Yes. I'm sorry. I know this is hard. But, where can I find her?", "Where can I find her?", null);
		yield break;
	}


	// .............
	// #42: lump

	void passage42_Init()
	{
		this.Passages[@"lump"] = new StoryPassage(@"lump", new string[]{  }, passage42_Main);
	}

	IStoryThread passage42_Main()
	{
		yield return text("I'm... ok. So you can't make a love potion?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("No, but you know what? I'll help you. I have an idea, but you have to let me trust you, ok?", "trust", null);
		yield return lineBreak();
		yield return link("No.", "No.", null);
		yield break;
	}


	// .............
	// #43: No.

	void passage43_Init()
	{
		this.Passages[@"No."] = new StoryPassage(@"No.", new string[]{  }, passage43_Main);
	}

	IStoryThread passage43_Main()
	{
		yield return text("Ok...");
		yield return lineBreak();
		yield return text("I'm sorry to have taken up your time. then.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Raeth la'en", "Fine.", null);
		yield break;
	}


}